// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PassengersController from "./passengers_controller"
application.register("passengers", PassengersController)

import TogglerController from "./toggler_controller"
application.register("toggler", TogglerController)
